### ISSUE TITLE
Pas de traduction dans la gestion des applications=>notifications

### ISSUE THREAD

**Issue by DJDirtboy** [pmspr4100/MA-XML-10-FRENCH#2]
Les parametres de notifications ne sont pas traduites
![notifications](https://user-images.githubusercontent.com/47698910/56085762-20f40f80-5e49-11e9-8e4f-34fa69e0cd5b.png)

**Comment by pmspr4100** [comment]
Ok merci des propositions de traduction ??

**Comment by pmspr4100** [comment]
Ok merci pour l'info
Quelques propositions de traduction.

**Comment by DJDirtboy** [comment]
"Show desktop app icon badge" => "Bulle sur l'icône de l'application"
"Show notifications on the lock screen" => "Afficher les notifications sur l'écran de verrouillage" 
"Pop up notifications at the top of screen" => "Autoriser les notifications importantes en haut de l'écran"
"Allow sound" => "Sons"
"Allow vibration" => "Vibrations"
"Allow breathing light tips" => "Voyant de notification"

"BERICHTEN" => "NOTIFICATIONS"

"Notification about messages" => "Notifications de Messages"  NB:Messages est le nom de l'application dans ce cas.

**Comment by pmspr4100** [comment]
Ok merci 
Pour moi les traductions sont OK sur mes fichiers.
