### ISSUE TITLE
Restore values-fr-rFR in framework-res.apk

### ISSUE THREAD

**Issue by IgorEisberg** [pmspr4100/MA-XML-10-FRENCH#3]
Never remove or change the values-fr-rFR in framework-res.apk.
This is required for French to be displayed in Language selection screen.

https://github.com/pmspr4100/MA-XML-10-FRENCH/tree/d3c119d363232c43e382cb5d8d2b6c05fc27b3b0/French/main/framework-res.apk/res

https://github.com/pmspr4100/MA-XML-10-FRENCH/tree/master/French/main/framework-res.apk/res

**Comment by pmspr4100** [comment]
Ok I did not think it would affect the French language.
It's corrected
