### ISSUE TITLE
Bug Camera sur Mi9 9.6.27

### ISSUE THREAD

**Issue by yeahmantiptap** [pmspr4100/MA-XML-10-FRENCH#4]
Bonjour,
Il y a un bug avec la caméra depuis cette version (9.6.27) sur le Mi9 (et peut-être d'autres appareils ?)
On ne peut pas sélectionner le mode grand angle, le mode 48Mp a disparu et le mode portrait fait crash l'appli caméra.
Si je passe le téléphone en Anglais, tout fonctionne bien.
J'ai fait une vidéo du bug ici : [Lien Youtube](https://www.youtube.com/watch?v=Ru5O4FYejIM)

Merci pour la trad en tout cas ;)

**Comment by ingbrzy** [comment]
Does it work with EN language? if issue is same on EN, it is not a translation issue..

**Comment by yeahmantiptap** [comment]
Yes, camera works great in English after a reboot. But still same problem when switching back to French. Tried wiping cache and data of camera app, problem still there.

**Comment by yeahmantiptap** [comment]
D'après l'utilisateur Meuhmeuh2005 sur le forum xiaomi.eu, le problème persiste sur la nouvelle mise à jour (9.7.4).
Lien du post : [Xiaomi.eu](https://xiaomi.eu/community/threads/9-7-4.51243/post-493458)

**Comment by pmspr4100** [comment]
Salut je viens de vérifié sur mon Redmi Note 7 pour le moment aucun bug. 
Je ne vois pas de ligne suspect au niveau de la traduction pouvant générer ce bug. 
Voir la réponse des admin xiaomi.eu

**Comment by yeahmantiptap** [comment]
Salut,
Surtout que entre la version 9.6.20 et 9.6.27 il doit pas y avoir beaucoup de différence niveau traduction de l'app Caméra. Je ne comprends pas ce qui provoque ce bug non plus.
J'ai essayé pas mal de truc, mais le bug persiste sur les Mi9.
J'ai même essayé une remise à zéro complet avec flash de la rom global du site mi.com via Fastboot + réinstallation de TWRP puis réinstallation de la rom 9.6.27 suivi d'une restauration d'usine après tout ça.
Toujours même problème.

**Comment by yeahmantiptap** [comment]
J'ai fais un comparatif du fichier strings.xml de l'app caméra entre la version du 9.6.17 et celle du 9.7.3. Voici les différences que j'ai trouvé : 

Nouvelles lignes dans Strings.xml entre la version 9.6.17 et 9.7.3 :

    <string name="pref_video_volumekey_function_default">shutter</string>
    <string name="pref_watermark_off">Désactivé</string>
    <string name="pref_watermark_on">Activé</string>
    <string name="pref_watermark_title">Filigrane</string>
    <string name="device_feature_configuration_file_name">défaut</string>
    <string name="device_ultra_pixel_watermark_default_text">DOUBLE APPAREIL PHOTO 48MP</string>
    <string name="pref_camera_long_pressing_viewfinder_entry_google_lens">Google Lens</string>
    <string name="pref_camera_long_pressing_viewfinder_entry_lock_ae_af">Verrouillage AE/AF</string>
    <string name="pref_camera_lying_summary">"Avertir de l'orientation actuelle lorsque le téléphone est parallèle au sol"</string>
    <string name="pref_camera_lying_title">"Notifier sur l'orientation"</string>
    <string name="pref_hdr_value_default">désactivé</string>
    <string name="user_define_watermark_cancel">Annuler</string>
    <string name="user_define_watermark_save">Sauvegarder</string>
    <string name="zoom_no_support_tip_64M">Le zoom ne fonctionne pas en mode 64MP</string>


Ligne retirée depuis :

    <string name="pref_camera_picturesize_entry_fullscreen">Plein écran 16:9</string>


Rien de bien folichon. Et surtout, pourquoi le bug n'existe que sur Mi9 ???

**Comment by jb-boin** [comment]
Idem sur le Mi9 SE.

**Comment by pmspr4100** [comment]
Je ne vois pas mon 2ème HMNote 7 sur l'officielle Global génère ce bug aléatoire pour moi cela doit venir de la rom officielle sur certains mobile

**Comment by pmspr4100** [comment]
Merci de faire un test matérielle dans l'application Sécurité ( tout en bas ) test matériel

**Comment by yeahmantiptap** [comment]
Le test est OK partout, plutôt logique vu que tout fonctionne bien en 9.6.20

**Comment by pmspr4100** [comment]
Franchement je vois pas parce que sur la traduction rien d'anormale.
@ingbrzy 
@IgorEisberg 
Where can the problem come from?
The translation is correct though

**Comment by ingbrzy** [comment]
probably fixed by https://github.com/pmspr4100/MA-XML-10-FRENCH/commit/f8ab505d9275efb4beb65e3b0dad23a255a60cd1
