### ISSUE TITLE
Batterie statistiques 

### ISSUE THREAD

**Issue by woupss** [pmspr4100/MA-XML-10-FRENCH#5]
Bonjour,
Il semble que dans la ROM xiaomi.eu version 9.8.1 les statistiques de la batterie ne sont pas traduits en français (tout est en anglais) 
Merci

**Comment by pmspr4100** [comment]
Oui pas eux le temps de traduire cela sera corrigé.

**Comment by pmspr4100** [comment]
Corrigé
